name: dr-onboard-autonomy

services:
  dr-onboard-autonomy:
    build: ..
    depends_on: []
      # - mqtt_local
      # - roscore
    cap_add:
      - SYS_TIME
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
      - "PYTHONUNBUFFERED=x"
    command: /bin/sh -c "while sleep 1000; do :; done"

  mqtt_local:
    image: eclipse-mosquitto:2
    volumes:
      - ./mqtt/drone-response.conf:/mosquitto/config/mosquitto.conf
    ports:
      # Use non-standard port to prevent conflicts with the ground control mqtt
      # This can happen when running the simulator and GCS on the same machine.
      - 1884:1883/tcp

  roscore:
    build: ./roscore
    ports:
      - 11311:11311/tcp
    command: stdbuf -o L roscore

  mavros:
    build: ./mavros
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
  
  ardupilot:
    build: ./ardupilot
    ports:
      - 8080:8080/tcp
      - 5762:5762/tcp
      - 5763:5763/tcp
    volumes:
      - ./ardupilot/scripts/start_simulation.sh:/usr/local/bin/start_simulation.sh
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: screen -S mavproxy -D -m  start_simulation.sh 

  px4:
    build: ./px4
    ports:
      - 8080:8080/tcp
      - 16000:16000/udp
      - 18570:18570/udp
    extra_hosts:
      - "host.qgc:host-gateway"
      - "host.docker.internal:host-gateway"
    volumes:
      - ./px4/px4-rc.mavlink:/home/user/Firmware/build/px4_sitl_default/etc/init.d-posix/px4-rc.mavlink
      - ./px4/px4-rc.params:/home/user/Firmware/build/px4_sitl_default/etc/init.d-posix/px4-rc.params
      - ./px4/scripts/start_simulation.sh:/bin/start_simulation.sh
      - ./px4/scripts/start_simulation_multi.sh:/bin/start_simulation_multi.sh
      - ./px4/scripts/start_simulated_scenario.sh:/bin/start_simulated_scenario.sh
    environment:
      - HEADLESS=1
      - NO_PXH=1
      - PX4_HOME_LAT=41.606695229356276
      - PX4_HOME_LON=-86.35561433514731
      - PX4_HOME_ALT=229.0
    command: start_simulation.sh