name: dr-onboard-autonomy

services:
  unit_tests:
    build: ..
    working_dir: /catkin_ws/src/dr_onboard_autonomy
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"

    volumes:
      - ..:/catkin_ws/src/dr_onboard_autonomy:cached
    # command: bash --init-file /catkin_ws/devel/setup.bash
    command: bash -c '. /catkin_ws/devel/setup.bash ; pytest test'

  gh_actions_unit_tests:
    build: ..
    working_dir: /catkin_ws/src/dr_onboard_autonomy
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: bash -c '. /catkin_ws/devel/setup.bash ; pytest test -v'

  gh_actions_bvh_tests:
    build: ..
    working_dir: /catkin_ws/src/dr_onboard_autonomy
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"

    volumes:
      - ${TERRAIN_DATA_DIR}:/usr/local/share/terrain/:cached

    command: bash -c '. /catkin_ws/devel/setup.bash ; pytest -p no:cacheprovider ./integration/bvh_integration_test.py -v'