version: "3.9"

services:
  roscore:
    build: ./roscore
    command: stdbuf -o L roscore
  
  mavros:
    build: ./mavros
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    ports:
      - "14540:14540/udp"
    command: ["stdbuf", "-o", "L", "roslaunch", "--wait", "mavros", "px4.launch", "fcu_url:=udp://:14540@:192.168.63.122:14580"]
  
  mqtt:
    ports:
      - 1883:1883/tcp
    build: ./mqtt

  mqtt_local:
    build: ./mqtt


  dr_onboard:
    depends_on:
      - mavros
      - mqtt_local
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    build: .

  dev:
    build: .
    depends_on:
      - mavros
      - mqtt
      - mqtt_local
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    volumes:
      - .:/catkin_ws/src/dr_onboard_autonomy
      # - ./src:/catkin_ws/src/dr_onboard_autonomy/src
      # - ./nodes:/catkin_ws/src/dr_onboard_autonomy/nodes
      # - ./launch:/catkin_ws/src/dr_onboard_autonomy/launch
    command: bash
